'use client';

import { useState } from 'react';
import { ParticleConstellation } from '@/components/system/ParticleConstellation';
import { usePersistentMatchState } from './usePersistentMatchState';
import { HALL_CATEGORIES, HALL_NEARBY_PLACES, HALL_ROAD_VISIBILITY_OPTIONS, type HallCategoryId, type HallNearbyPlaceId, type HallRoadVisibilityId } from '@/domain/event-hall-registration';
import type { EventHallMatchIntelligenceResponse } from '@/domain/event-hall-match-intelligence';

export function EventHallMatchSearch() {
  const [searchStep, setSearchStep] = useState(1);
  const [county, setCounty] = usePersistentMatchState('hall-match:county', ''); const [townOrCity, setTownOrCity] = usePersistentMatchState('hall-match:townOrCity', ''); const [estateOrArea, setEstateOrArea] = usePersistentMatchState('hall-match:estateOrArea', '');
  const [roadVisibility, setRoadVisibility] = usePersistentMatchState<HallRoadVisibilityId[]>('hall-match:roadVisibility', []); const [hallCategory, setHallCategory] = usePersistentMatchState<HallCategoryId[]>('hall-match:hallCategory', []); const [minimumCapacity, setMinimumCapacity] = usePersistentMatchState('hall-match:minimumCapacity', ''); const [maximumBookingPrice, setMaximumBookingPrice] = usePersistentMatchState('hall-match:maximumBookingPrice', '');
  const [nearbyPlaces, setNearbyPlaces] = usePersistentMatchState<HallNearbyPlaceId[]>('hall-match:nearbyPlaces', []);  const [aiSearchDescription, setAiSearchDescription] = usePersistentMatchState('hall-match:aiSearchDescription', ''); const [bookingAvailability, setBookingAvailability] = usePersistentMatchState<'available'|'any'>('hall-match:bookingAvailability', 'available'); const [requestedDate, setRequestedDate] = usePersistentMatchState('hall-match:requestedDate', ''); const [requestedTime, setRequestedTime] = usePersistentMatchState('hall-match:requestedTime', ''); const [message, setMessage] = useState(''); const [response, setResponse] = useState<EventHallMatchIntelligenceResponse | null>(null); const [searching, setSearching] = useState(false);
  function toggle<T extends string>(value:T,setter:React.Dispatch<React.SetStateAction<T[]>>) { setter((current)=>current.includes(value)?current.filter((item)=>item!==value):[...current,value]); }
  async function search(){ setSearching(true); setMessage(''); const result=await fetch('/api/match/event-hall/intelligent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({county,townOrCity,estateOrArea,roadVisibility,hallCategory,minimumCapacity:minimumCapacity?Number(minimumCapacity):undefined,maximumBookingPrice:maximumBookingPrice?Number(maximumBookingPrice):undefined,nearbyPlaces,aiSearchDescription,bookingAvailability,requestedDate:requestedDate||undefined,requestedTime:requestedTime||undefined})}); const data=await result.json(); setResponse(data); setSearching(false); setMessage(data.cards?.length?'Best matching halls prepared.':'No exact hall matches yet. PataSpace avoids empty results where suitable alternatives exist.'); } if (searching) { return (<section className="property-registration-card match-wizard" aria-labelledby="hall-match-title"><ParticleConstellation message="Finding matching event halls..." /></section>); }
  return <section className="property-registration-card match-wizard" aria-labelledby="hall-match-title"><div className="auth-header"><span className="section-eyebrow">Hall Match</span><h1 id="hall-match-title">Find a venue for your event</h1><p>Choose your event requirements. PataSpace uses registration, verification and booking availability data behind the scenes.</p></div><div className="match-progress" aria-label="Hall Match progress">{[1,2,3,4].map((item)=><button key={item} type="button" className={searchStep===item?'step active':'step'} onClick={()=>setSearchStep(item)}>{item}</button>)}</div><div className="wizard-step-label">Step {searchStep} of 4</div><div className="auth-step">
    {searchStep===1?<section className="wizard-panel"><h2>Location and budget</h2><div className="nearby-grid"><label className="field-label">County<input value={county} onChange={(e)=>setCounty(e.target.value)} placeholder="Nairobi" /></label><label className="field-label">Town / City<input value={townOrCity} onChange={(e)=>setTownOrCity(e.target.value)} placeholder="Nairobi" /></label><label className="field-label">Estate / Area<input value={estateOrArea} onChange={(e)=>setEstateOrArea(e.target.value)} placeholder="Westlands" /></label><label className="field-label">Minimum Hall Capacity<input type="number" value={minimumCapacity} onChange={(e)=>setMinimumCapacity(e.target.value)} /></label><label className="field-label">Maximum Booking Price <small>Tell us your maximum booking price budget.</small><input type="number" value={maximumBookingPrice} onChange={(e)=>setMaximumBookingPrice(e.target.value)} /></label><label className="field-label">Maximum Deposit <small>(optional)</small><input type="number" disabled placeholder="Not required for event hall search" /></label></div></section>:null}
    {searchStep===2?<section className="wizard-panel"><h2>Availability and timing</h2><fieldset className="selection-fieldset"><legend>Booking Availability</legend><label><input type="radio" checked={bookingAvailability==='available'} onChange={()=>setBookingAvailability('available')} /> Available for bookings</label><label><input type="radio" checked={bookingAvailability==='any'} onChange={()=>setBookingAvailability('any')} /> Any registered availability</label></fieldset><label className="field-label">Event Date (optional)<input type="date" value={requestedDate} onChange={(e)=>setRequestedDate(e.target.value)} /></label><label className="field-label">Preferred Time (optional)<input type="time" value={requestedTime} onChange={(e)=>setRequestedTime(e.target.value)} /></label><div className="auth-message">Water Information and Electricity Information are not used for Hall Match. When you specify a date and time, halls will be matched and displayed with their real-time status: Open and Available, Open but Booked, or Closed at the requested time.</div></section>:null}
    {searchStep===3?<section className="wizard-panel"><h2>Hall type, visibility, and preferences</h2><fieldset className="selection-fieldset"><legend>Hall Category</legend>{HALL_CATEGORIES.map((item)=><label key={item.id}><input type="checkbox" checked={hallCategory.includes(item.id)} onChange={()=>toggle(item.id,setHallCategory)} /> {item.label}</label>)}</fieldset><fieldset className="selection-fieldset"><legend>Road Visibility</legend>{HALL_ROAD_VISIBILITY_OPTIONS.map((item)=><label key={item.id}><input type="checkbox" checked={roadVisibility.includes(item.id)} onChange={()=>toggle(item.id,setRoadVisibility)} /> {item.label}</label>)}</fieldset><fieldset className="selection-fieldset"><legend>Nearby Places</legend>{HALL_NEARBY_PLACES.map((item)=><label key={item.id}><input type="checkbox" checked={nearbyPlaces.includes(item.id)} onChange={()=>toggle(item.id,setNearbyPlaces)} /> {item.label}</label>)}</fieldset><label className="field-label">Tell us more to help us find your ideal property.<textarea className="large-description-field" rows={5} value={aiSearchDescription} onChange={(e)=>setAiSearchDescription(e.target.value)} placeholder="Describe anything else that matters to you." /></label></section>:null}
    {searchStep===4?<section className="wizard-panel"><h2>Review and submit</h2><div className="review-summary-card"><p><strong>Location:</strong> {[estateOrArea,townOrCity,county].filter(Boolean).join(', ')||'Not specified'}</p><p><strong>Capacity:</strong> {minimumCapacity || 'Not specified'} · Price {maximumBookingPrice?`KES ${Number(maximumBookingPrice).toLocaleString()}`:'Not specified'}</p><p><strong>Event Date:</strong> {requestedDate || 'Not specified'} · <strong>Time:</strong> {requestedTime || 'Not specified'}</p></div><button className="primary-action" type="button" onClick={search}>Prepare Hall Matches</button></section>:null}
    <div className="wizard-controls"><button type="button" className="secondary-action" disabled={searchStep===1} onClick={()=>setSearchStep((s)=>Math.max(1,s-1))}>Back</button>{searchStep<4?<button type="button" className="primary-action" onClick={()=>setSearchStep((s)=>Math.min(4,s+1))}>Continue</button>:null}</div>{message?<div className="auth-message" role="status" aria-live="polite">{message}</div>:null}{response?<div className="review-summary-card"><h3>Approved hall result batch</h3><p>{response.cards.length} hall card(s) prepared from {response.limitedBatch.totalQualifiedMatches} qualified match(es).</p><p>Smart Rotation: {response.smartRotation.applied?'Prepared for future batches':'Not needed for this search'}.</p></div>:null}{response?.cards.map((card)=><article className="info-card property-result-card" key={card.result.resultId}><div className="property-image-frame"><span aria-hidden="true">🎉</span></div><div className="property-card-body"><div className="property-card-topline"><span className="badge">{card.result.verificationStatus==='verified'?'Verified':'Verification pending'}</span><span className="match-score">Match {Math.max(70,100-card.rank*3)}%</span></div><h3>{card.result.hallName} · {card.result.matchedHallIdentifiers.join(', ')}</h3><p className="property-location">{card.result.location.estateOrAreaOrNeighbourhood || card.result.location.townOrCity}, {card.result.location.county}</p><div style={{display: 'flex', gap: '0.5rem', alignItems: 'center', margin: '0.5rem 0'}}><span className="badge" style={{backgroundColor: card.result.timeStatus==='open-and-available'?'#22c55e':card.result.timeStatus==='open-but-booked'?'#f59e0b':'#ef4444', color: '#fff', padding: '0.25rem 0.5rem', borderRadius: '0.25rem', fontSize: '0.75rem'}}>{card.result.timeStatus==='open-and-available'?'✓ Open & Available':card.result.timeStatus==='open-but-booked'?'⏰ Open but Booked':'✕ Closed'}</span></div><p className="property-price">{card.result.bookingPrice!=null?`KES ${card.result.bookingPrice.toLocaleString()}`:'Price available in listing summary'}</p><p><strong>Summary:</strong> {card.summary.text}</p><ul>{card.whyThisHallMatches.map((reason)=><li key={reason.id}>{reason.label}</li>)}</ul><p>Unlock This Listing: KES {card.unlockThisListing.price.amount}</p><p>{card.verifiedAccess.recommended?'Verified Access recommended. Individual hall unlock remains available.':'Individual Unlock This Listing is prioritized. Verified Access remains available.'}</p><div className="hero-actions"><button className="primary-action" type="button">Unlock This Listing</button><button className="secondary-action" type="button">Verified Access</button></div><p>Contact details, WhatsApp, additional photos, and Request Viewing unlock after access is granted.</p><p>Reviews become available after the event has taken place.</p></div></article>)}</div></section>;
}
