'use client';

import { useState } from 'react';
import { usePersistentMatchState } from './usePersistentMatchState';
import { BUSINESS_SUITABILITY_OPTIONS, COMMERCIAL_UNIT_TYPES, ROAD_VISIBILITY_OPTIONS, SHOP_NEARBY_PLACES, SHOP_WATER_AVAILABILITY_OPTIONS, type BusinessSuitabilityId, type CommercialUnitTypeId, type RoadVisibilityId, type ShopNearbyPlaceId, type ShopWaterAvailabilityId } from '@/domain/shop-registration';
import type { ShopMatchIntelligenceResponse } from '@/domain/shop-match-intelligence';

export function ShopMatchSearch() {
  const [searchStep, setSearchStep] = useState(1);
  const [county, setCounty] = usePersistentMatchState('shop-match:county', ''); const [townOrCity, setTownOrCity] = usePersistentMatchState('shop-match:townOrCity', ''); const [estateOrArea, setEstateOrArea] = usePersistentMatchState('shop-match:estateOrArea', '');
  const [roadVisibility, setRoadVisibility] = usePersistentMatchState<RoadVisibilityId[]>('shop-match:roadVisibility', []); const [maximumMonthlyRent, setMaximumMonthlyRent] = usePersistentMatchState('shop-match:maximumMonthlyRent', ''); const [maximumDeposit, setMaximumDeposit] = usePersistentMatchState('shop-match:maximumDeposit', '');
  const [businessSuitability, setBusinessSuitability] = usePersistentMatchState<BusinessSuitabilityId[]>('shop-match:businessSuitability', []); const [commercialUnitTypes, setCommercialUnitTypes] = usePersistentMatchState<CommercialUnitTypeId[]>('shop-match:commercialUnitTypes', []); const [waterAvailability, setWaterAvailability] = usePersistentMatchState<ShopWaterAvailabilityId[]>('shop-match:waterAvailability', []);
  const [electricityRequired, setElectricityRequired] = usePersistentMatchState<'yes'|'no'|'any'>('shop-match:electricityRequired', 'any'); const [nearbyPlaces, setNearbyPlaces] = usePersistentMatchState<ShopNearbyPlaceId[]>('shop-match:nearbyPlaces', []); const [aiSearchDescription, setAiSearchDescription] = usePersistentMatchState('shop-match:aiSearchDescription', '');
  const [message, setMessage] = useState(''); const [response, setResponse] = useState<ShopMatchIntelligenceResponse | null>(null);
  function toggle<T extends string>(value: T, setter: React.Dispatch<React.SetStateAction<T[]>>) { setter((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); }
  async function search() { setMessage('Finding matching shops...'); const result = await fetch('/api/match/shop/intelligent', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ county, townOrCity, estateOrArea, roadVisibility, maximumMonthlyRent: maximumMonthlyRent ? Number(maximumMonthlyRent) : undefined, maximumDeposit: maximumDeposit ? Number(maximumDeposit) : undefined, businessSuitability, commercialUnitTypes, waterAvailability, electricityRequired, nearbyPlaces, aiSearchDescription }) }); const data = await result.json(); setResponse(data); setMessage(data.cards?.length ? 'Best matching shops prepared.' : 'No exact shop matches yet. PataSpace avoids empty results where suitable alternatives exist.'); }
  return <section className="property-registration-card match-wizard" aria-labelledby="shop-match-title"><div className="auth-header"><span className="section-eyebrow">Shop Match</span><h1 id="shop-match-title">Find a shop for your business</h1><p>Choose what matters for your business. PataSpace uses verified registration and vacancy data behind the scenes.</p></div><div className="match-progress" aria-label="Shop Match progress">{[1,2,3,4].map((item)=><button key={item} type="button" className={searchStep===item?'step active':'step'} onClick={()=>setSearchStep(item)}>{item}</button>)}</div><div className="wizard-step-label">Step {searchStep} of 4</div><div className="auth-step">
    {searchStep===1?<section className="wizard-panel"><h2>Location and budget</h2><div className="nearby-grid"><label className="field-label">County<input value={county} onChange={(e)=>setCounty(e.target.value)} placeholder="Nairobi" /></label><label className="field-label">Town / City<input value={townOrCity} onChange={(e)=>setTownOrCity(e.target.value)} placeholder="Nairobi" /></label><label className="field-label">Estate / Area<input value={estateOrArea} onChange={(e)=>setEstateOrArea(e.target.value)} placeholder="Westlands" /></label><label className="field-label">Tell us your maximum monthly rent budget<input type="number" value={maximumMonthlyRent} onChange={(e)=>setMaximumMonthlyRent(e.target.value)} /></label><label className="field-label">Maximum Deposit <small>(optional)</small><input type="number" value={maximumDeposit} onChange={(e)=>setMaximumDeposit(e.target.value)} /></label></div></section>:null}
    {searchStep===2?<section className="wizard-panel"><h2>Utilities</h2><fieldset className="selection-fieldset"><legend>Water Information</legend>{SHOP_WATER_AVAILABILITY_OPTIONS.map((item)=><label key={item.id}><input type="checkbox" checked={waterAvailability.includes(item.id)} onChange={()=>toggle(item.id,setWaterAvailability)} /> {item.label}</label>)}</fieldset><fieldset className="selection-fieldset"><legend>Electricity Required?</legend><label><input type="radio" checked={electricityRequired==='any'} onChange={()=>setElectricityRequired('any')} /> Any</label><label><input type="radio" checked={electricityRequired==='yes'} onChange={()=>setElectricityRequired('yes')} /> Yes</label><label><input type="radio" checked={electricityRequired==='no'} onChange={()=>setElectricityRequired('no')} /> No</label></fieldset></section>:null}
    {searchStep===3?<section className="wizard-panel"><h2>Visibility, suitability, and preferences</h2><fieldset className="selection-fieldset"><legend>Road Visibility</legend>{ROAD_VISIBILITY_OPTIONS.map((item)=><label key={item.id}><input type="checkbox" checked={roadVisibility.includes(item.id)} onChange={()=>toggle(item.id,setRoadVisibility)} /> {item.label}</label>)}</fieldset><fieldset className="selection-fieldset"><legend>Business Suitability</legend>{BUSINESS_SUITABILITY_OPTIONS.map((item)=><label key={item.id}><input type="checkbox" checked={businessSuitability.includes(item.id)} onChange={()=>toggle(item.id,setBusinessSuitability)} /> {item.label}</label>)}</fieldset><fieldset className="selection-fieldset"><legend>Commercial Unit Type</legend>{COMMERCIAL_UNIT_TYPES.map((item)=><label key={item.id}><input type="checkbox" checked={commercialUnitTypes.includes(item.id)} onChange={()=>toggle(item.id,setCommercialUnitTypes)} /> {item.label}</label>)}</fieldset><fieldset className="selection-fieldset"><legend>Nearby Places</legend>{SHOP_NEARBY_PLACES.map((item)=><label key={item.id}><input type="checkbox" checked={nearbyPlaces.includes(item.id)} onChange={()=>toggle(item.id,setNearbyPlaces)} /> {item.label}</label>)}</fieldset><label className="field-label">Tell us more to help us find your ideal property.<textarea className="large-description-field" rows={5} value={aiSearchDescription} onChange={(e)=>setAiSearchDescription(e.target.value)} placeholder="Describe anything else that matters to you." /></label></section>:null}
    {searchStep===4?<section className="wizard-panel"><h2>Review and submit</h2><div className="review-summary-card"><p><strong>Location:</strong> {[estateOrArea,townOrCity,county].filter(Boolean).join(', ')||'Not specified'}</p><p><strong>Budget:</strong> {maximumMonthlyRent?`KES ${Number(maximumMonthlyRent).toLocaleString()}`:'Not specified'} · Deposit optional {maximumDeposit?`KES ${Number(maximumDeposit).toLocaleString()}`:'not entered'}</p></div><button className="primary-action" type="button" onClick={search}>Prepare Shop Matches</button></section>:null}
    <div className="wizard-controls"><button type="button" className="secondary-action" disabled={searchStep===1} onClick={()=>setSearchStep((s)=>Math.max(1,s-1))}>Back</button>{searchStep<4?<button type="button" className="primary-action" onClick={()=>setSearchStep((s)=>Math.min(4,s+1))}>Continue</button>:null}</div>{message?<div className="auth-message" role="status" aria-live="polite">{message}</div>:null}{response?<div className="review-summary-card"><h3>Approved shop result batch</h3><p>{response.cards.length} shop card(s) prepared from {response.limitedBatch.totalQualifiedMatches} qualified match(es).</p><p>Smart Rotation: {response.smartRotation.applied?'Prepared for future batches':'Not needed for this search'}.</p></div>:null}{response?.cards.map((card)=><article className="info-card property-result-card" key={card.result.resultId}><div className="property-image-frame"><span aria-hidden="true">🏪</span></div><div className="property-card-body"><div className="property-card-topline"><span className="badge">{card.result.verificationStatus==='verified'?'Verified':'Verification pending'}</span><span className="match-score">Match {Math.max(70,100-card.rank*3)}%</span></div><h3>{(Array.isArray(card.result.shopType) ? card.result.shopType.join(', ') : card.result.shopType).replaceAll('-', ' ')} · {card.result.matchedUnitIdentifier}</h3><p className="property-location">{card.result.location.estateOrAreaOrNeighbourhood || card.result.location.townOrCity}, {card.result.location.county}</p><p className="property-price">{card.result.monthlyRent!==null?`KES ${card.result.monthlyRent.toLocaleString()} / month`:'Price available in listing summary'}</p><p><strong>Summary:</strong> {card.aiSummary.text}</p><ul>{card.whyThisShopMatches.map((reason)=><li key={reason.id}>{reason.label}</li>)}</ul><p>Unlock This Listing: KES {card.unlockThisListing.price.amount}</p><p>{card.verifiedAccess.recommended?'Verified Access recommended. Individual shop unlock remains available.':'Individual Unlock This Listing is prioritized. Verified Access remains available.'}</p><div className="hero-actions"><button className="primary-action" type="button">Unlock This Listing</button><button className="secondary-action" type="button">Verified Access</button></div><p>Contact details, WhatsApp, and Request Viewing unlock after access is granted.</p></div></article>)}</div></section>;
}
