import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const domain = readFileSync(new URL('../src/domain/ai-admin-assistant.ts', import.meta.url), 'utf8');
const service = readFileSync(new URL('../src/server/ai-admin/service.ts', import.meta.url), 'utf8');
const foundation = readFileSync(new URL('../src/lib/foundation.ts', import.meta.url), 'utf8');
const page = readFileSync(new URL('../app/admin/ai-assistant/page.tsx', import.meta.url), 'utf8');
const dashboard = readFileSync(new URL('../src/components/dashboard/DashboardShell.tsx', import.meta.url), 'utf8');

assert.ok(domain.includes('internalOnly: true'), 'AI Admin Assistant must be internal only');
assert.ok(domain.includes('isChatbot: false'), 'AI Admin Assistant must not be a chatbot');
assert.ok(domain.includes('visibleToCustomers: false'), 'AI Admin Assistant must be invisible to customers');
assert.ok(domain.includes('operatesInBackground: true'), 'AI Admin Assistant must operate in background');
for (const phrase of ['customersInteractWithAi: false','customersAskAiQuestions: false','customersKnowAiIsOperating: false','customersTriggerAiManually: false']) assert.ok(domain.includes(phrase), `Invisible Intelligence missing ${phrase}`);
for (const support of ['Property verification','Duplicate property detection','Duplicate vacancy detection','Missing registration information','Suspicious account activity','Vacancy confirmation monitoring','Review moderation assistance','Notification delivery monitoring','Payment anomaly detection','Platform health monitoring']) assert.ok(domain.includes(support), `Admin support missing ${support}`);
for (const issue of ['Missing information','Inconsistent information','Possible duplicate registrations','Unusual registration behaviour','Incomplete photo uploads','Verification anomalies']) assert.ok(domain.includes(issue), `Verification assistance missing ${issue}`);
for (const match of ['House Match','Shop Match','Office Match','Event Hall Match','Matching failures','Poor search results','Duplicate search results','Ranking inconsistencies']) assert.ok(domain.includes(match), `Match monitoring missing ${match}`);
assert.ok(domain.includes('changesFounderApprovedMatchRules: false'), 'AI must not change Match Engine rules');
for (const payment of ['Failed payments','Duplicate payment attempts','Payment recovery events','Missing receipts','Payment processing failures']) assert.ok(domain.includes(payment), `Payment monitoring missing ${payment}`);
for (const review of ['Spam','Offensive reviews','Duplicate reviews','Suspicious review activity','Potential fake reviews']) assert.ok(domain.includes(review), `Review monitoring missing ${review}`);
for (const notification of ['Failed notifications','Duplicate notifications','Delayed notifications','Delivery failures']) assert.ok(domain.includes(notification), `Notification monitoring missing ${notification}`);
for (const vacancy of ['Daily Vacancy Confirmation compliance','Long-unconfirmed vacancies','Frequently changing vacancy status','Unusual vacancy patterns']) assert.ok(domain.includes(vacancy), `Vacancy monitoring missing ${vacancy}`);
for (const field of ['Clear explanation','Reason for the recommendation','Suggested action','Priority level']) assert.ok(domain.includes(field), `Recommendation field missing ${field}`);
assert.ok(domain.includes('administratorAlwaysMakesFinalDecision: true'), 'Administrator final decision missing');
assert.ok(domain.includes('aiDoesNotOverrideFounderApprovedWorkflows: true'), 'AI must not override workflows');
for (const rule of ['mustNeverChangeFounderApprovedPricing: true','mustNeverChangeAccessRules: true','mustNeverChangeVerificationRules: true','mustNeverChangeMatchEngineRules: true','mustNeverChangeCustomerAccessControlRules: true','onlyFounderCanApproveBusinessRuleChanges: true']) assert.ok(domain.includes(rule), `Learning principle missing ${rule}`);
assert.ok(domain.includes('accessOnlyRequiredInformation: true'), 'Data minimisation missing');
assert.ok(domain.includes('customerPrivacyAlwaysPreserved: true'), 'Customer privacy missing');
assert.ok(domain.includes('platformSecurityAlwaysPreserved: true'), 'Platform security missing');
assert.ok(domain.includes('AI_ADMIN_ASSISTANT_SCOPE'), 'Assistant data scope missing');
assert.ok(domain.includes('aiAdminCanAccessRole'), 'AI Admin role access helper missing');
assert.ok(service.includes('addAiAdminRecommendation'), 'Recommendation creation service missing');
assert.ok(service.includes('listAiAdminRecommendations'), 'Recommendation list service missing');
assert.ok(service.includes('updateAiAdminRecommendationStatus'), 'Recommendation status update service missing');
assert.ok(service.includes('runAiAdminFoundationScan'), 'Foundation scan service missing');
assert.ok(foundation.includes('aiAdminAssistant: AI_ADMIN_ASSISTANT_FOUNDATION'), 'Foundation snapshot must expose AI Admin Assistant');
assert.ok(foundation.includes('aiAdminAssistantScope: AI_ADMIN_ASSISTANT_SCOPE'), 'Foundation snapshot must expose AI Admin scope');
assert.ok(page.includes('Internal only'), 'Admin page must label internal only');
assert.ok(page.includes('invisible to customers'), 'Admin page must preserve invisible principle');
assert.ok(dashboard.includes('/admin/ai-assistant'), 'Admin dashboard link missing');

console.log('PataSpace AI Admin Assistant foundation checks passed.');
