import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const domain = readFileSync(new URL('../src/domain/ai-admin-workspace.ts', import.meta.url), 'utf8');
const service = readFileSync(new URL('../src/server/ai-admin-workspace/service.ts', import.meta.url), 'utf8');
const foundation = readFileSync(new URL('../src/lib/foundation.ts', import.meta.url), 'utf8');
const page = readFileSync(new URL('../app/admin/ai-workspace/page.tsx', import.meta.url), 'utf8');
const dashboard = readFileSync(new URL('../src/components/dashboard/DashboardShell.tsx', import.meta.url), 'utf8');

assert.ok(domain.includes('preservesInvisibleIntelligencePrinciple: true'), 'Invisible Intelligence must be preserved');
assert.ok(domain.includes('customersCanSeeWorkspace: false'), 'Workspace must not be visible to customers');
assert.ok(domain.includes('supportsAdministratorsNotReplaceThem: true'), 'AI must support administrators, not replace them');
for (const level of ['level1SilentOperations', 'level2AiSummaryAndRecommendations', 'level3ImmediateCriticalAlerts']) assert.ok(domain.includes(level), `Missing decision framework ${level}`);
for (const silent of ['Retrying failed notifications','Removing duplicate notifications','Receipt regeneration','Background synchronisation','Temporary communication retries','Routine health checks','Temporary cache issues','Minor platform optimisations']) assert.ok(domain.includes(silent), `Missing silent operation ${silent}`);
for (const summary of ['Possible duplicate properties','Possible duplicate reviews','Properties awaiting verification','Long-pending verification requests','Frequently changing vacancy status','High customer interest properties','Search behaviour trends','Platform performance trends','Payment success statistics','Verification workload','Review moderation trends']) assert.ok(domain.includes(summary), `Missing summary item ${summary}`);
for (const alert of ['Payment fraud attempts','Fake payment confirmations','Account takeover attempts','Mass spam attacks','Database integrity issues','Critical API failures','Platform outages','Security breaches','Verification service failures','Major payment system failures']) assert.ok(domain.includes(alert), `Missing critical alert ${alert}`);
for (const field of ['whatDetected','whyAttentionMayBeRequired','confidenceLevel','suggestedAction']) assert.ok(domain.includes(field), `Recommendation missing ${field}`);
assert.ok(domain.includes('neverAssumeFromNameDescriptionOrPhotosAlone: true'), 'Duplicate property rule missing');
for (const indicator of ['GPS location','Registered property location','Building identity','Unit identifiers','Registration information','Registered Property Owner','Registered Property Manager','Registered Leasing Agent']) assert.ok(domain.includes(indicator), `Duplicate indicator missing ${indicator}`);
assert.ok(domain.includes('finalDecisionBelongsToAdministrator: true'), 'Admin final duplicate decision missing');
for (const review of ['Repeated identical reviews','Spam content','Offensive language','Coordinated review behaviour','Unusual review activity']) assert.ok(domain.includes(review), `Review intelligence missing ${review}`);
assert.ok(domain.includes('neverAutomaticallyRemovesLegitimateReviews: true'), 'AI must not remove legitimate reviews');
for (const payment of ['Payment success rates','Failed transactions','Duplicate payment attempts','Missing receipts','Payment recovery events','Suspicious payment activity']) assert.ok(domain.includes(payment), `Payment intelligence missing ${payment}`);
for (const verification of ['Missing registration information','Poor quality property photos','Unusual registration behaviour','Long-pending verification requests','Repeated verification failures']) assert.ok(domain.includes(verification), `Verification intelligence missing ${verification}`);
for (const vacancy of ['Daily Vacancy Confirmation compliance','Frequently changing vacancy status','Long-unconfirmed vacancies','Unusual vacancy patterns']) assert.ok(domain.includes(vacancy), `Vacancy intelligence missing ${vacancy}`);
for (const rule of ['mustNeverModifyFounderApprovedPricing','mustNeverModifyUnlockThisListingRules','mustNeverModifyVerifiedAccessRules','mustNeverModifyMatchEngineRules','mustNeverModifyVerificationRules','mustNeverModifyCustomerAccessControlRules','mustNeverModifyViewingWorkflow','mustNeverModifyBusinessLogic','onlyFounderMayApproveBusinessRuleChanges']) assert.ok(domain.includes(`${rule}: true`), `Learning principle missing ${rule}`);
assert.ok(domain.includes('finalDecisionAlwaysWithAdministrator: true'), 'Administrator control missing');
assert.ok(domain.includes('aiMustNeverSilentlyApproveRejectDeleteOrModifyCriticalDecisions: true'), 'AI critical decision restriction missing');
for (const sec of ['protectCustomerPrivacy','protectPropertyInformation','protectPaymentInformation','protectAdministratorActions','secureOperationalLogs','fullyAuditableAiActivities']) assert.ok(domain.includes(`${sec}: true`), `Security missing ${sec}`);
for (const overview of ['activeProperties','activeCustomers','activePropertyOwners','activePropertyManagers','activeLeasingAgents','verificationQueue','paymentSuccessRate','notificationDeliveryRate','dailyVacancyConfirmationCompliance','platformHealthStatus']) assert.ok(domain.includes(overview), `Health overview missing ${overview}`);
assert.ok(service.includes('buildAiPlatformSummary'), 'AI Summary service missing');
assert.ok(service.includes('buildPlatformHealthOverview'), 'Platform Health Overview service missing');
assert.ok(service.includes('buildAiWorkspaceRecommendations'), 'Recommendation service missing');
assert.ok(service.includes('buildCriticalAlerts'), 'Critical alert service missing');
assert.ok(page.includes("Today's Platform Summary"), 'Workspace page missing AI Summary');
assert.ok(page.includes('Platform Health Overview'), 'Workspace page missing health overview');
assert.ok(page.includes('invisible to customers'), 'Workspace page must preserve invisibility');
assert.ok(dashboard.includes('/admin/ai-workspace'), 'Admin dashboard link missing');
assert.ok(foundation.includes('aiAdminWorkspace: AI_ADMIN_WORKSPACE_FOUNDATION'), 'Foundation snapshot must expose AI Admin Workspace');

console.log('PataSpace AI Admin Workspace checks passed.');
