import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const domain = readFileSync(new URL('../src/domain/viewing.ts', import.meta.url), 'utf8');
const service = readFileSync(new URL('../src/server/viewings/service.ts', import.meta.url), 'utf8');
const foundation = readFileSync(new URL('../src/lib/foundation.ts', import.meta.url), 'utf8');
const dashboard = readFileSync(new URL('../src/components/dashboard/DashboardShell.tsx', import.meta.url), 'utf8');
const page = readFileSync(new URL('../app/dashboard/viewings/page.tsx', import.meta.url), 'utf8');

for (const category of ['Houses', 'Shops', 'Offices', 'Event Halls']) assert.ok(domain.includes(category), `Viewing must apply to ${category}`);
assert.ok(domain.includes('requiresActiveEntitlement: true'), 'Viewing must require active entitlement');
assert.ok(domain.includes('customersWithoutAccessCanSubmitViewingRequests: false'), 'Customers without access must not submit requests');
assert.ok(service.includes('getActiveUnlockForTarget'), 'Viewing eligibility must check Unlock This Listing');
assert.ok(service.includes('hasVerifiedAccessToTarget'), 'Viewing eligibility must check Verified Access');
assert.ok(service.includes('Unlock This Listing or Verified Access is required'), 'No-access error missing');
for (const control of ['Toggle buttons', 'Date picker', 'Time selector', 'Optional note field']) assert.ok(domain.includes(control), `Missing guided control ${control}`);
for (const status of ['pending', 'accepted', 'rescheduled', 'declined', 'cancelled', 'completed']) assert.ok(domain.includes(`'${status}'`), `Missing status ${status}`);
assert.ok(service.includes('preferredDate') && service.includes('preferredTime'), 'Viewing date/time collection missing');
assert.ok(service.includes('customerName') && service.includes('customerPhone'), 'Customer details inclusion missing');
assert.ok(service.includes('propertyOrUnitIdentifier'), 'Property or unit identifier missing');
assert.ok(service.includes('requestTimestamp'), 'Request timestamp missing');
assert.ok(service.includes('responsibleContactRole'), 'Responsible contact role missing');
assert.ok(service.includes('respondToViewing'), 'Viewing response workflow missing');
assert.ok(service.includes("input.action === 'accept'"), 'Accept response missing');
assert.ok(service.includes("input.action === 'suggest-different-time'"), 'Reschedule suggestion missing');
assert.ok(service.includes("input.action === 'decline'"), 'Decline response missing');
assert.ok(service.includes('cancelViewing'), 'Cancellation workflow missing');
assert.ok(service.includes('completeViewing'), 'Completion workflow missing');
assert.ok(service.includes('customerCompletionResponse'), 'Customer completion response missing');
assert.ok(service.includes('responsibleContactCompletionResponse'), 'Responsible contact completion response missing');
assert.ok(service.includes('reviewInvitationAvailableAfterCompletedViewing'), 'Review preparation missing');
assert.ok(service.includes('eventHallReviewAfterEventDate'), 'Event Hall review after event rule missing');
assert.ok(domain.includes('24-hours-before') && domain.includes('2-hours-before'), 'Viewing reminders missing');
assert.ok(service.includes('checkViewingPropertyEligibility'), 'Property availability eligibility check missing');
assert.ok(service.includes('getVerificationRecord'), 'Verification check missing');
assert.ok(service.includes('getVacancyConfirmationRecordsForProperty'), 'Vacancy eligibility check missing for houses/shops/offices');
assert.ok(service.includes('readEventHallStore'), 'Hall availability check missing');
assert.ok(domain.includes('completeAuditTrailRequired: true'), 'Audit trail requirement missing');
assert.ok(service.includes('auditTrail'), 'Audit trail implementation missing');
assert.ok(service.includes('getViewingHistoryForCustomer'), 'Customer viewing history missing');
assert.ok(service.includes('getViewingHistoryForResponsibleContact'), 'Responsible contact viewing history missing');
assert.ok(foundation.includes('viewingWorkflow: VIEWING_WORKFLOW_FOUNDATION'), 'Foundation snapshot must expose viewing workflow');
assert.ok(dashboard.includes('/dashboard/viewings'), 'Dashboard must link viewing history');
assert.ok(page.includes('Viewing history'), 'Viewing history page missing');

console.log('PataSpace viewing workflow checks passed.');
