import { requireCurrentUser } from '@/server/auth/current-user';
import { getFounderAiSummary, getFounderApprovalCases, getFounderAuditTrail, getFounderDashboardOverview } from '@/server/founder-admin/service';

export const metadata = { title: 'Founder Dashboard — PataSpace' };

export default async function FounderDashboardPage() {
  await requireCurrentUser('/admin/dashboard');
  const [overview, summary, cases, audit] = await Promise.all([getFounderDashboardOverview(), getFounderAiSummary(), getFounderApprovalCases(), getFounderAuditTrail()]);
  return <main className="dashboard-page"><section className="dashboard-card"><span className="badge">Founder Command Centre</span><h1>Founder Administration Dashboard</h1><p>The Founder is the highest authority. AI Operations Officer assists but never overrides Founder decisions.</p><div className="cards-grid"><article className="info-card"><h3>Active Customers</h3><p>{overview.activeCustomers}</p></article><article className="info-card"><h3>Registered Properties</h3><p>{overview.registeredProperties}</p></article><article className="info-card"><h3>Verified Properties</h3><p>{overview.verifiedProperties}</p></article><article className="info-card"><h3>Pending Verifications</h3><p>{overview.pendingVerifications}</p></article><article className="info-card"><h3>Active Unlocks</h3><p>{overview.activeUnlockThisListingPurchases}</p></article><article className="info-card"><h3>Active Verified Access</h3><p>{overview.activeVerifiedAccessPurchases}</p></article><article className="info-card"><h3>Viewing Requests</h3><p>{overview.viewingRequests}</p></article><article className="info-card"><h3>Platform Health</h3><p>{overview.platformHealthStatus}</p></article></div><div className="review-summary-card"><h3>AI Summary Panel</h3><p>{summary.propertiesAwaitingVerification} properties awaiting verification.</p><p>{summary.possibleDuplicatePropertyRegistrations} possible duplicate properties.</p><p>{summary.suspiciousReviewPatterns} suspicious review patterns.</p><p>Payment success rate: {summary.paymentSuccessRate}</p><p>{summary.notificationsAutomaticallyRecovered} notifications automatically recovered.</p><p>{summary.repeatedVacancyStatusChanges} repeated vacancy status changes.</p></div><h2>Founder Approval Centre</h2><div className="role-list">{cases.map((item)=><article key={item.id}><h3>{item.caseSummary}</h3><p><strong>Evidence:</strong> {item.supportingEvidence.join(' ')}</p><p><strong>AI confidence:</strong> {item.aiConfidenceLevel}</p><p><strong>Recommended action:</strong> {item.recommendedAction}</p><div className="hero-actions"><button className="primary-action" type="button">Approve</button><button className="secondary-action" type="button">Reject</button><button className="secondary-action" type="button">Request further review</button></div></article>)}</div><h2>Audit Trail</h2><div className="role-list">{audit.slice(0,10).map((entry)=><article key={entry.id}><h3>{entry.actionType}</h3><p>{entry.summary}</p><p>{new Date(entry.createdAt).toLocaleString()}</p></article>)}{!audit.length ? <article><h3>No Founder actions yet</h3><p>Approvals, rejections, pricing changes, business rule changes, security actions and manual overrides will appear here.</p></article> : null}</div></section></main>;
}
