import { requireCurrentUser } from '@/server/auth/current-user';
import { getSecurityAnalytics, getSecurityTimeline, listSecurityCases, runSecurityIntelligenceScan } from '@/server/security-operations/service';

export const metadata = { title: 'Security Operations Centre — PataSpace' };

export default async function SecurityOperationsPage() {
  await requireCurrentUser('/admin/dashboard');
  await runSecurityIntelligenceScan();
  const [cases, analytics, timeline] = await Promise.all([listSecurityCases(), getSecurityAnalytics(), getSecurityTimeline()]);
  return <main className="dashboard-page"><section className="dashboard-card"><span className="badge">Security Operations Centre</span><h1>Security Operations Centre</h1><p>Invisible to normal users. Investigates first, recommends actions second, and escalates to the Founder only when genuinely necessary.</p><div className="cards-grid"><article className="info-card"><h3>Active Security Status</h3><p>{analytics.activeInvestigations ? 'Investigations active' : 'Stable'}</p></article><article className="info-card"><h3>Active Investigations</h3><p>{analytics.activeInvestigations}</p></article><article className="info-card"><h3>Fraud Cases Awaiting Review</h3><p>{cases.filter((c)=>c.currentStatus === 'founder-review-required').length}</p></article><article className="info-card"><h3>Platform Protection Status</h3><p>{analytics.platformProtectionPerformance}</p></article></div><h2>Fraud Case Management</h2><div className="role-list">{cases.map((item)=><article key={item.id}><h3>{item.category} · {item.currentStatus}</h3><p><strong>Case ID:</strong> {item.id}</p><p><strong>AI Summary:</strong> {item.aiInvestigationSummary}</p><p><strong>Confidence:</strong> {item.confidenceLevel}</p><p><strong>Recommended action:</strong> {item.recommendedAction}</p><p><strong>Evidence:</strong> {item.supportingEvidence.map((e)=>e.detail).join(' ')}</p><div className="hero-actions"><button className="primary-action" type="button">Approve</button><button className="secondary-action" type="button">Reject</button><button className="secondary-action" type="button">Request additional investigation</button><button className="secondary-action" type="button">Continue monitoring</button><button className="secondary-action" type="button">Close case</button></div></article>)}</div><h2>Security Analytics</h2><div className="review-summary-card"><p>Investigations: {analytics.numberOfInvestigations}</p><p>Resolved: {analytics.investigationsResolved}</p><p>AI investigation accuracy: {analytics.aiInvestigationAccuracy}</p><p>Repeat offender trends: {analytics.repeatOffenderTrends}</p></div><h2>Security Timeline</h2><div className="role-list">{timeline.map((event)=><article key={event.id}><h3>{event.title}</h3><p>{event.summary}</p><p>{new Date(event.occurredAt).toLocaleString()}</p></article>)}</div></section></main>;
}
