import { requireCurrentUser } from '@/server/auth/current-user';
import { buildAiPlatformSummary, buildAiWorkspaceRecommendations, buildCriticalAlerts, buildPlatformHealthOverview } from '@/server/ai-admin-workspace/service';

export const metadata = { title: 'AI Admin Workspace — PataSpace' };

export default async function AiAdminWorkspacePage() {
  await requireCurrentUser('/admin/dashboard');
  const [summary, recommendations, criticalAlerts, health] = await Promise.all([
    buildAiPlatformSummary(), buildAiWorkspaceRecommendations(), buildCriticalAlerts(), buildPlatformHealthOverview()
  ]);
  return <main className="dashboard-page"><section className="dashboard-card"><span className="badge">Internal AI Workspace</span><h1>AI Admin Workspace</h1><p>The AI Admin Workspace is invisible to customers. AI assists administrators and never replaces final administrator decisions.</p><div className="review-summary-card"><h3>Today's Platform Summary</h3><p>{summary.possibleDuplicatePropertyRegistrations} possible duplicate property registrations detected.</p><p>{summary.suspiciousReviewPatterns} suspicious review patterns detected.</p><p>{summary.propertiesAwaitingVerification} properties awaiting verification.</p><p>Payment success rate: {summary.paymentSuccessRate}.</p><p>{summary.notificationsAutomaticallyRecovered} notifications were automatically recovered.</p><p>{summary.repeatedVacancyStatusChanges} properties experienced repeated vacancy status changes.</p></div><div className="review-summary-card"><h3>Platform Health Overview</h3><p>Active properties: {health.activeProperties}</p><p>Active customers: {health.activeCustomers}</p><p>Active Property Owners: {health.activePropertyOwners}</p><p>Active Property Managers: {health.activePropertyManagers}</p><p>Active Leasing Agents: {health.activeLeasingAgents}</p><p>Verification queue: {health.verificationQueue}</p><p>Payment success rate: {health.paymentSuccessRate}</p><p>Notification delivery rate: {health.notificationDeliveryRate}</p><p>Daily Vacancy Confirmation compliance: {health.dailyVacancyConfirmationCompliance}</p><p>Status: {health.platformHealthStatus}</p></div><div className="role-list">{criticalAlerts.map((alert) => <article key={alert.id}><h3>{alert.title}</h3><p>{alert.explanation}</p><span className="badge">Critical</span></article>)}{recommendations.map((item) => <article key={item.id}><h3>{item.whatDetected}</h3><p><strong>Why:</strong> {item.whyAttentionMayBeRequired}</p><p><strong>Confidence:</strong> {item.confidenceLevel}</p><p><strong>Suggested action:</strong> {item.suggestedAction}</p><span className="badge">{item.priority}</span></article>)}</div></section></main>;
}
