import { requireCurrentUser } from '@/server/auth/current-user';
import { getCustomerDashboardSnapshot } from '@/server/customer-dashboard/service';

export const metadata = { title: 'Customer Dashboard — PataSpace' };

export default async function CustomerDashboardPage() {
  const profile = await requireCurrentUser('/customer/home');
  const snapshot = await getCustomerDashboardSnapshot(profile);
  return <main className="dashboard-page"><section className="dashboard-card"><span className="badge">Customer Dashboard</span><h1>My PataSpace</h1><p>Manage your searches, access, viewings, reviews, notifications, payments, receipts and account activity.</p><div className="cards-grid"><a className="info-card" href="/profile/settings"><h3>My Profile</h3><p>{snapshot.profile.fullName}<br />{snapshot.profile.email}<br />{snapshot.profile.phoneNumber}</p></a><a className="info-card" href="/match/house"><h3>My Saved Properties</h3><p>{snapshot.savedProperties.length} saved property/properties.</p></a><a className="info-card" href="/dashboard/viewings"><h3>My Viewing Requests</h3><p>{snapshot.viewingRequests.length} viewing request(s).</p></a><a className="info-card" href="/dashboard/reviews"><h3>My Reviews</h3><p>{snapshot.reviews.length} review(s).</p></a><a className="info-card" href="/dashboard/notifications"><h3>My Notifications</h3><p>{snapshot.notifications.filter((n) => n.status === 'unread').length} unread notification(s).</p></a><article className="info-card"><h3>My Unlocked Properties</h3><p>{snapshot.unlockedProperties.length} unlocked property/unit record(s).</p>{snapshot.unlockedProperties.slice(0, 3).map((unlock) => <p key={unlock.id}>{unlock.target.unitIdentifier} · {unlock.target.propertyCategory} · {unlock.unlockedAt ? `Unlocked ${new Date(unlock.unlockedAt).toLocaleDateString()}` : 'Unlock date pending'} · Expires {unlock.unlockExpiresAt ? new Date(unlock.unlockExpiresAt).toLocaleString() : 'after payment confirmation'} · {unlock.remainingUnlockTime?.display ?? 'Remaining time pending'} · {unlock.displayStatus ?? 'Unlocked'}</p>)}</article><article className="info-card"><h3>My Verified Access</h3><p>{snapshot.verifiedAccess.filter((access) => access.status === 'active').length ? 'Verified Access Active' : 'Verified Access inactive'}</p>{snapshot.verifiedAccess.slice(0, 3).map((access) => <p key={access.id}>Purchased {access.activatedAt ? new Date(access.activatedAt).toLocaleDateString() : 'pending'} · Expires {access.expiresAt ? new Date(access.expiresAt).toLocaleString() : 'pending'} · {access.intelligence?.remainingTime.display ?? 'Remaining time pending'} · {access.scope.propertyCategory}</p>)}</article><article className="info-card"><h3>My Payments</h3><p>{snapshot.payments.length} payment record(s).</p></article><article className="info-card"><h3>My Receipts</h3><p>{snapshot.receipts.length} receipt(s) available.</p></article><article className="info-card"><h3>Search History</h3><p>{snapshot.searchHistory.length} previous search(es).</p></article></div></section></main>;
}
