import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const domain = readFileSync(new URL('../src/domain/analytics.ts', import.meta.url), 'utf8');
const service = readFileSync(new URL('../src/server/analytics/service.ts', import.meta.url), 'utf8');
const foundation = readFileSync(new URL('../src/lib/foundation.ts', import.meta.url), 'utf8');
const dashboard = readFileSync(new URL('../src/components/dashboard/DashboardShell.tsx', import.meta.url), 'utf8');
const page = readFileSync(new URL('../app/admin/analytics/page.tsx', import.meta.url), 'utf8');
const propertyService = readFileSync(new URL('../src/server/properties/service.ts', import.meta.url), 'utf8');
const houseMatchService = readFileSync(new URL('../src/server/match/house-match-service.ts', import.meta.url), 'utf8');
const viewingService = readFileSync(new URL('../src/server/viewings/service.ts', import.meta.url), 'utf8');
const reviewService = readFileSync(new URL('../src/server/reviews/service.ts', import.meta.url), 'utf8');

assert.ok(domain.includes('centralizedAnalyticsEngine: true'), 'Central analytics engine missing');
assert.ok(domain.includes('operatesQuietlyInBackground: true'), 'Analytics must operate quietly');
assert.ok(domain.includes('doesNotAffectCustomerExperience: true'), 'Analytics must not affect customer experience');
assert.ok(domain.includes('collectsMeaningfulDataOnly: true'), 'Analytics should collect meaningful data only');
assert.ok(domain.includes('duplicateOrUnnecessaryAnalyticsNeverCollected: true'), 'Duplicate analytics prevention rule missing');
for (const area of ['Platform growth','Customer behaviour','Property performance','Revenue performance','Operational efficiency','Market trends']) assert.ok(domain.includes(area), `Missing Founder understanding area ${area}`);
for (const module of ['Authentication','Property Registration','Property Verification','House Match','Shop Match','Office Match','Event Hall Match','Unlock This Listing','Verified Access','Payment System','Viewing Workflow','Reviews & Ratings','Notifications','Customer Dashboard','AI Admin Assistant','Founder Dashboard']) assert.ok(domain.includes(module), `Missing module coverage ${module}`);
for (const event of ['account-registration','login','property-search','saved-property','unlock-purchase','verified-access-purchase','viewing-request','review-submitted','property-registration','property-verification','vacancy-publication','vacancy-update','vacancy-confirmation','property-availability-change','payment-initiated','payment-completed','payment-failed','payment-recovery','receipt-generation','viewing-requested','viewing-accepted','viewing-rescheduled','viewing-cancelled','viewing-completed','review-edited','review-reported','review-response-added']) assert.ok(domain.includes(`'${event}'`), `Missing event type ${event}`);
for (const metric of ['Platform response times','Search performance','Match Engine performance','Verification performance','Payment performance','Notification delivery','Viewing workflow performance']) assert.ok(domain.includes(metric), `Missing performance metric ${metric}`);
for (const item of ['Registration growth','Verification rates','Vacancy trends','Occupancy trends','Property availability','Property popularity']) assert.ok(domain.includes(item), `Missing property analytics ${item}`);
for (const item of ['Search frequency','Favourite property categories','Viewing request activity','Unlock purchasing behaviour','Verified Access usage','Review participation']) assert.ok(domain.includes(item), `Missing customer behaviour ${item}`);
for (const geo of ['Counties','Towns','Estates','Neighbourhoods']) assert.ok(domain.includes(geo), `Missing geographic analytics ${geo}`);
for (const op of ['Verification workload','Daily Vacancy Confirmation compliance','Customer support workload','AI Operations workload','Payment reliability','Notification reliability']) assert.ok(domain.includes(op), `Missing operational analytics ${op}`);
for (const ai of ['Trends','Operational bottlenecks','Unusual behaviour','Growth opportunities','Areas requiring Founder attention']) assert.ok(domain.includes(ai), `Missing AI analytics ${ai}`);
for (const quality of ['accurateDataCollection','duplicatePrevention','consistentReporting','reliableCalculations','secureStorage','neverCompromisePlatformPerformance']) assert.ok(domain.includes(`${quality}: true`), `Missing data quality ${quality}`);
assert.ok(domain.includes('respectsCustomerPrivacy: true'), 'Privacy rule missing');
assert.ok(domain.includes('personalInformationNotExposedByDefault: true'), 'Personal information redaction missing');
assert.ok(service.includes('trackAnalyticsEvent'), 'Track analytics service missing');
assert.ok(service.includes('duplicate'), 'Analytics duplicate prevention missing');
assert.ok(service.includes('getAnalyticsSummary'), 'Analytics summary missing');
assert.ok(service.includes('listAnalyticsEvents'), 'Analytics event history missing');
assert.ok(foundation.includes('analytics: ANALYTICS_FOUNDATION'), 'Foundation snapshot must expose analytics');
assert.ok(dashboard.includes('/admin/analytics'), 'Admin dashboard must link analytics');
assert.ok(page.includes('Platform Analytics'), 'Analytics page missing');
for (const source of [propertyService, houseMatchService, viewingService, reviewService]) assert.ok(source.includes('trackAnalyticsEvent'), 'Core workflows must track analytics events');

console.log('PataSpace analytics foundation checks passed.');
