import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const domain = readFileSync(new URL('../src/domain/executive-intelligence.ts', import.meta.url), 'utf8');
const service = readFileSync(new URL('../src/server/executive-intelligence/service.ts', import.meta.url), 'utf8');
const page = readFileSync(new URL('../app/admin/executive/intelligence/page.tsx', import.meta.url), 'utf8');
const foundation = readFileSync(new URL('../src/lib/foundation.ts', import.meta.url), 'utf8');
for (const q of ['Where should PataSpace grow next?','Which property categories require expansion?','Which counties require more recruitment?','Which business opportunities deserve immediate attention?','Which previous strategies worked?','Which strategies need adjustment?']) assert.ok(domain.includes(q), `Missing strategic question ${q}`);
assert.ok(domain.includes('everyRecommendationSupportedByEvidence: true'), 'Evidence requirement missing');
for (const item of ['Revenue Today','Revenue This Week','Revenue This Month','New Customers','New Property Registrations','New Verified Properties','Critical Platform Issues','Active Business Opportunities','Active Business Goals','AI Strategic Recommendations']) assert.ok(domain.includes(item), `Executive brief missing ${item}`);
for (const county of ['Customer demand','Search volume','Failed searches','Property registrations','Verified properties','Revenue generated','Search success rate','Property supply']) assert.ok(domain.includes(county), `County intelligence missing ${county}`);
for (const source of ['Search Opportunity Intelligence','Failed Search Intelligence','Business Opportunity Queue','County Performance','Platform Analytics','Revenue Intelligence','Registration Trends','Property Supply']) assert.ok(domain.includes(source), `Goal source missing ${source}`);
for (const action of ['Accept Goal','Modify Goal','Reject Goal']) assert.ok(domain.includes(action), `Founder approval action missing ${action}`);
assert.ok(domain.includes('aiNeverActivatesGoalsAutomatically: true'), 'AI must not activate goals');
for (const field of ['Goal Name','Target','Current Progress','Completion Percentage','Remaining Target','Current Status']) assert.ok(domain.includes(field), `Active goal field missing ${field}`);
for (const loop of ['Customer Searches','Search Opportunity Intelligence','Business Opportunity Queue','AI Executive Recommendation','Founder Approval','Active Business Goal','AI Progress Tracking','Business Outcome Review','Continuous Improvement','New Strategic Recommendations']) assert.ok(domain.includes(loop), `Improvement loop missing ${loop}`);
assert.ok(service.includes('getExecutiveBrief'), 'Executive brief service missing');
assert.ok(service.includes('getCountyPerformanceIntelligence'), 'County intelligence service missing');
assert.ok(service.includes('buildAiStrategicRecommendations'), 'Strategic recommendations service missing');
assert.ok(service.includes('recommendBusinessGoals'), 'Business goal recommendation service missing');
assert.ok(service.includes('decideBusinessGoal'), 'Founder approval workflow missing');
assert.ok(service.includes('updateBusinessGoalProgress'), 'Progress tracking missing');
assert.ok(service.includes('generateBusinessOutcomeReports'), 'Outcome report missing');
assert.ok(page.includes('Executive Brief'), 'Page missing Executive Brief');
assert.ok(page.includes('Accept Goal') && page.includes('Modify Goal') && page.includes('Reject Goal'), 'Page missing goal decisions');
assert.ok(foundation.includes('executiveIntelligence: EXECUTIVE_INTELLIGENCE_FOUNDATION'), 'Foundation snapshot missing executive intelligence');
console.log('PataSpace executive intelligence checks passed.');
