import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const passwordSource = readFileSync(new URL('../src/server/auth/password.ts', import.meta.url), 'utf8');
const authStore = readFileSync(new URL('../src/server/auth/store.ts', import.meta.url), 'utf8');
const authDomain = readFileSync(new URL('../src/domain/auth.ts', import.meta.url), 'utf8');
const registerForm = readFileSync(new URL('../src/components/auth/RegisterForm.tsx', import.meta.url), 'utf8');
const loginForm = readFileSync(new URL('../src/components/auth/LoginForm.tsx', import.meta.url), 'utf8');
const proxy = readFileSync(new URL('../proxy.ts', import.meta.url), 'utf8');
const migration = readFileSync(new URL('../supabase/migrations/0001_pataspace_production_schema.sql', import.meta.url), 'utf8') + '\n' + readFileSync(new URL('../supabase/migrations/0002_production_auth_profiles.sql', import.meta.url), 'utf8') + '\n' + readFileSync(new URL('../supabase/migrations/0003_auth_uniqueness_and_indexes.sql', import.meta.url), 'utf8') + '\n' + readFileSync(new URL('../supabase/migrations/0004_identity_account_security.sql', import.meta.url), 'utf8');

assert.ok(passwordSource.includes('bcrypt'), 'Production password hashing must use bcrypt');
assert.ok(passwordSource.includes('bcrypt.hash'), 'Password hashing must call bcrypt.hash');
assert.ok(passwordSource.includes('bcrypt.compare'), 'Password verification must use bcrypt.compare');
assert.ok(!passwordSource.includes('scrypt('), 'Production password hashing must not use legacy scrypt implementation');
assert.ok(authStore.includes('from users') && authStore.includes('user_profiles') && authStore.includes('sessions') && authStore.includes('password_resets'), 'Auth store must use normalized Supabase tables');
assert.ok(!authStore.includes('json-store'), 'Auth store must not use JSON document compatibility storage');
assert.ok(!authStore.includes('node:fs'), 'Auth store must not use filesystem persistence');
for (const table of ['account_types', 'login_history']) assert.ok(migration.includes(table), `Migration must include ${table}`);
for (const type of ['customer-tenant', 'property-owner', 'property-manager', 'leasing-agent', 'administrator', 'founder']) assert.ok(migration.includes(type), `Account type missing: ${type}`);
assert.ok(authDomain.includes('phoneNumber: string'), 'Phone number must be primary auth input');
assert.ok(authDomain.includes('Google Sign-In'), 'Google Sign-In must be supported');
assert.ok(authDomain.includes('rememberMe?: boolean'), 'Login input must support Remember Me');
assert.ok(registerForm.includes('Continue with Google') && loginForm.includes('Continue with Google'), 'Google Sign-In options must be visible');
assert.ok(registerForm.includes('👁 Show Password') && registerForm.includes('🙈 Hide Password'), 'Registration must keep show/hide password');
assert.ok(loginForm.includes('👁 Show Password') && loginForm.includes('🙈 Hide Password'), 'Login must keep show/hide password');
assert.ok(!registerForm.includes('Platform Admin'), 'Public registration must not expose Platform Admin');
assert.ok(proxy.includes('pataspace_session'), 'Authentication proxy must check session cookie');
assert.ok(proxy.includes('X-Frame-Options') && proxy.includes('X-Content-Type-Options'), 'Security headers must be configured');
assert.ok(authStore.includes("return 'customer-tenant'") && authStore.includes("return 'administrator'"), 'Role-to-account-type mapping must support customer/admin account types');
console.log('PataSpace production authentication checks passed.');
