import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const domain = readFileSync(new URL('../src/domain/recommendation-engine.ts', import.meta.url), 'utf8');
const service = readFileSync(new URL('../src/server/recommendations/service.ts', import.meta.url), 'utf8');
const foundation = readFileSync(new URL('../src/lib/foundation.ts', import.meta.url), 'utf8');
const page = readFileSync(new URL('../app/admin/recommendations/page.tsx', import.meta.url), 'utf8');
const dashboard = readFileSync(new URL('../src/components/dashboard/DashboardShell.tsx', import.meta.url), 'utf8');

for (const category of ['Houses','Shops','Offices','Event Halls']) assert.ok(domain.includes(category), `Applies to ${category}`);
assert.ok(domain.includes('customerRequirementsAlwaysFirst: true'), 'Customer requirements must be first');
assert.ok(domain.includes('matchScoreInvisibleToCustomers: true'), 'Match score must be invisible');
assert.ok(domain.includes('highestScoreBelongsToBestRequirementMatch: true'), 'Highest score rule missing');
assert.ok(domain.includes('popularityOnlyScoringForbidden: true'), 'Popularity-only scoring must be forbidden');
assert.ok(domain.includes('additionalFactorsOnlyRefineAfterMatchAccuracy: true'), 'Additional factors only after match accuracy');
for (const reason of ['Matches your preferred budget.','Located in your preferred area.','Matches your requested property type.','Matches your bedroom requirement.','Matches your parking preference.','Matches your water preference.','Matches your electricity preference.','Matches your security preference.','Matches your accessibility requirements.','Matches details from your description.']) assert.ok(domain.includes(reason), `Missing explanation ${reason}`);
assert.ok(domain.includes('inventedReasonsAllowed: false'), 'Explanations must not invent reasons');
assert.ok(domain.includes('originalTextUnchanged: true'), 'Original text must remain unchanged');
assert.ok(domain.includes('extractsPreferences'), 'AI description extraction missing');
for (const opt of ['Match accuracy','Search quality','Filter effectiveness','Recommendation quality','Customer interaction with search results']) assert.ok(domain.includes(opt), `Missing optimisation ${opt}`);
assert.ok(domain.includes('search-every-estate-and-neighbourhood-within-requested-town'), 'Recovery step 1 missing');
assert.ok(domain.includes('search-every-supported-area-within-requested-location'), 'Recovery step 2 missing');
assert.ok(domain.includes('suggest-nearby-towns-only-if-no-meaningful-matches-exist'), 'Recovery step 3 missing');
assert.ok(domain.includes('skipDirectlyToDistantLocations: false'), 'Must not skip to distant locations');
assert.ok(domain.includes('notifiesOnlyForHighQualityMatches: true'), 'Saved search notification quality missing');
assert.ok(domain.includes('avoidPoorMatches: true'), 'Avoid poor match notifications missing');
assert.ok(domain.includes('avoidDuplicateRecommendations: true'), 'Avoid duplicate recommendations missing');
assert.ok(domain.includes('avoidMinorImprovements: true'), 'Avoid minor improvements missing');
assert.ok(domain.includes('avoidRepetitiveListings: true'), 'Avoid repetitive listings missing');
assert.ok(domain.includes('avoidNearlyIdenticalFirstPage: true'), 'Recommendation diversity missing');
assert.ok(domain.includes('stillRespectsMatchAccuracy: true'), 'Diversity must respect match accuracy');
for (const rule of ['mustNeverModifyFounderApprovedMatchRanking','mustNeverModifyUnlockThisListingRules','mustNeverModifyVerifiedAccessRules','mustNeverModifyCustomerAccessControl','mustNeverChangePricing','mustNeverChangeBusinessRules']) assert.ok(domain.includes(`${rule}: true`), `AI learning rule missing ${rule}`);
assert.ok(domain.includes('customerSearchesRemainPrivate: true'), 'Customer searches privacy missing');
assert.ok(domain.includes('noCustomerSearchInformationSharedWithOtherUsers: true'), 'Search sharing privacy missing');
assert.ok(service.includes('explainRecommendation'), 'Recommendation explanation service missing');
assert.ok(service.includes('evaluateSavedSearch'), 'Saved search evaluation service missing');
assert.ok(service.includes('trackAnalyticsEvent'), 'Recommendation analytics integration missing');
assert.ok(foundation.includes('aiRecommendationEngine: AI_RECOMMENDATION_ENGINE_FOUNDATION'), 'Foundation snapshot missing recommendation engine');
assert.ok(page.includes('Match Accuracy remains the highest-ranking factor'), 'Admin page must state match accuracy priority');
assert.ok(dashboard.includes('/admin/recommendations'), 'Dashboard link missing');
console.log('PataSpace recommendation engine checks passed.');
