import { requireCurrentUser } from '@/server/auth/current-user';
import { getCustomerWorkspace } from '@/server/customer-workspace/service';

export const metadata = { title: 'Customer Workspace — PataSpace' };

export default async function CustomerWorkspacePage() {
  const profile = await requireCurrentUser('/customer/home');
  const workspace = await getCustomerWorkspace(profile);
  return <main className="dashboard-page"><section className="dashboard-card"><span className="badge">Personal Workspace</span><h1>My Workspace</h1><p>Your property journey is organised into simple cards. AI quietly keeps the workspace useful without making decisions for you.</p><div className="cards-grid">{workspace.insights.map((insight)=><article className="info-card" key={insight.id}><h3>{insight.label}</h3><p>{insight.value}</p></article>)}<article className="info-card"><h3>Saved Searches</h3><p>{workspace.savedSearches.length} saved search(es).</p><a href="/dashboard/customer">Open</a></article><article className="info-card"><h3>Saved Properties</h3><p>{workspace.dashboard.savedProperties.length} saved property/properties.</p><a href="/dashboard/customer">Open</a></article><article className="info-card"><h3>Recently Viewed</h3><p>{workspace.recentlyViewed.length} recently viewed item(s).</p>{workspace.recentlyViewed.slice(0,3).map((item)=><p key={item.id}>{item.unitIdentifier ?? item.propertyId} · {item.accessState}</p>)}</article><article className="info-card"><h3>Active Unlock This Listing</h3><p>{workspace.activeUnlocks.length} active unlock(s).</p>{workspace.activeUnlocks.slice(0,3).map((item)=><p key={item.id}>{item.target.unitIdentifier} · {item.remainingUnlockTime?.display ?? 'Countdown pending'}</p>)}</article><article className="info-card"><h3>Active Verified Access</h3><p>{workspace.activeVerifiedAccess.length} active entitlement(s).</p>{workspace.activeVerifiedAccess.slice(0,3).map((item)=><p key={item.id}>{item.scope.propertyCategory} · {item.intelligence?.remainingTime.display ?? '72-hour countdown pending'}</p>)}</article><article className="info-card"><h3>Viewing Requests</h3><p>{workspace.dashboard.viewingRequests.length} viewing request(s).</p><a href="/dashboard/viewings">Open</a></article><article className="info-card"><h3>Notifications</h3><p>{workspace.dashboard.notifications.length} notification(s).</p><a href="/dashboard/notifications">Open</a></article><article className="info-card"><h3>Settings</h3><p>Account information, password, notification preferences, saved search preferences and privacy settings.</p></article></div></section></main>;
}
